# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-23 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current_chapter', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Max_chapter', models.IntegerField()),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('Created',),
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Major', models.CharField(max_length=200)),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Major', models.CharField(blank=True, default='', max_length=200)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Birth', models.DateField()),
                ('Age', models.TextField()),
                ('Description', models.IntegerField()),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='Professor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lectures', to='sk.Professor'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='Lecture_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chapters', to='sk.Lecture'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='Chapter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Chapters', to='sk.Chapter'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='Lecture_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lectuers', to='sk.Lecture'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='Student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Students', to='sk.Student'),
        ),
    ]
