# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0003_lecture_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('Created',)},
        ),
        migrations.AlterField(
            model_name='student',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='Description',
            field=models.TextField(),
        ),
    ]
