# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-26 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0004_auto_20170825_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='Name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
